# system
mode: 0
distribute: True
num_parallel_workers: 8

# dataset
dataset: "imagenet"
data_dir: "/path/to/imagenet"
shuffle: True
dataset_download: False
batch_size: 64
drop_remainder: True

# augmentation
image_resize: 224
hflip: 0.5
color_jitter: 0.4
interpolation: "bilinear"
crop_pct: 0.875

# model
model: "shufflenet_v1_g3_05"
num_classes: 1000
pretrained: False
ckpt_path: ""
keep_checkpoint_max: 30
ckpt_save_dir: "./ckpt"
epoch_size: 250
dataset_sink_mode: True
amp_level: "O0"

# loss
loss: "CE"
label_smoothing: 0.1

# lr scheduler
scheduler: "cosine_decay"
min_lr: 0.0
lr: 0.35
warmup_epochs: 4
decay_epochs: 246

# optimizer
opt: "momentum"
weight_decay_filter: 'auto'
momentum: 0.9
weight_decay: 0.00004
loss_scale: 1024
use_nesterov: False
