# system
mode: 0
distribute: True
num_parallel_workers: 8

# dataset
dataset: 'imagenet'
data_dir: '/path/to/imagenet'
shuffle: True
dataset_download: False
batch_size: 64
drop_remainder: True

# augmentation
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
interpolation: 'bilinear'
crop_pct: 0.875

# model
model: 'mobilenet_v1_100'
num_classes: 1001
pretrained: False
ckpt_path: ''
keep_checkpoint_max: 80
ckpt_save_dir: './ckpt'
epoch_size: 200
dataset_sink_mode: True
amp_level: 'O2'

# loss
loss: 'CE'
label_smoothing: 0.1

# lr scheduler
scheduler: 'cosine_decay'
min_lr: 0.0
lr: 0.4
warmup_epochs: 2
decay_epochs: 198

# optimizer
opt: 'momentum'
momentum: 0.9
weight_decay: 0.00003
loss_scale: 1024
use_nesterov: False
