# system
mode: 0
distribute: True
num_parallel_workers: 16
val_while_train: True
val_interval: 1

# dataset
dataset: "imagenet"
data_dir: "/path/to/imagenet"
shuffle: True
dataset_download: False
batch_size: 64
drop_remainder: True

# augmentation
interpolation: "bicubic"
re_prob: 0.2
auto_augment: "randaug-m9-mstd0.5"
re_value: "random"

# model
model: "rexnet_15"
num_classes: 1000
pretrained: False
ckpt_path: ""
keep_checkpoint_max: 10
ckpt_save_dir: "./ckpt"
ckpt_save_policy: "top_k"
epoch_size: 400
dataset_sink_mode: True
amp_level: "O2"
drop_rate: 0.2
drop_path_rate: 0.1

# loss
loss: "CE"
label_smoothing: 0.1

# lr scheduler
scheduler: "cosine_decay"
min_lr: 1.0e-6
lr: 0.5
warmup_epochs: 30
decay_epochs: 370

# optimizer
opt: "sgd"
momentum: 0.9
weight_decay: 1.0e-5
loss_scale: 1024
use_nesterov: True
