# system
mode: 0
distribute: True
num_parallel_workers: 8
val_while_train: True
seed: 1

# dataset
dataset: 'imagenet'
data_dir: '/path/to/imagenet'
shuffle: True
dataset_download: False
batch_size: 256
drop_remainder: True
val_split: val

# augmentation
image_resize: 256
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
interpolation: 'bicubic'
crop_pct: 0.875
color_jitter: 0.4
re_prob: 0.0
cutmix: 1.0
cutmix_prob: 0.0
auto_augment: 'randaug-m9-mstd0.5-inc1'
ema: True
ema_decay: 0.9995

# model
model: 'edgenext_x_small'
num_classes: 1000
pretrained: False
ckpt_path: ''
keep_checkpoint_max: 10
val_interval: 2
ckpt_save_dir: './ckpt'
epoch_size: 350
dataset_sink_mode: True
amp_level: 'O3'
val_amp_level: 'O3'
drop_path_rate: 0.1

# loss
loss: 'CE'
label_smoothing: 0.1

# lr scheduler
scheduler: 'cosine_decay'
min_lr: 1e-6
lr: 4e-3
warmup_epochs: 20
decay_rate: 0.1
decay_epochs: 330

# optimizer
opt: 'adamw'
momentum: 0.9
weight_decay: 0.05
loss_scale: 1024
drop_overflow_update: True
use_nesterov: False
