# system
mode: 0
distribute: True
num_parallel_workers: 8
val_while_train: True
val_interval: 1

# dataset
dataset: "imagenet"
data_dir: "/data1/dataset/ImageNet/ILSVRC/Data/CLS-LOC/"
shuffle: True
dataset_download: False
batch_size: 128
drop_remainder: True

# augmentation
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
interpolation: "bilinear"
re_prob: 0.1
mixup: 0.2
cutmix: 1.0
cutmix_prob: 1.0
crop_pct: 0.875
color_jitter: [0., 0., 0.]
auto_augment: "trivialaugwide"

# model
model: "resnet50_ebv"
num_classes: 1000
pretrained: False
keep_checkpoint_max: 5
ckpt_save_policy: "top_k"
ckpt_save_dir: "./ckpt"
epoch_size: 205
dataset_sink_mode: True
amp_level: "O2"

# loss
loss: "CE"
label_smoothing: 0.1

# lr scheduler
scheduler: "cosine_decay"
lr: 0.1
min_lr: 0
warmup_epochs: 5
decay_epochs: 200
lr_epoch_stair: False

# optimizer
opt: "momentum"
momentum: 0.9
weight_decay: 0.00002
loss_scale: 1024
use_nesterov: False
